import Header from 'components/header';
import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
     
        <Head>
          <title>碳通科技</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport"/>
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header href="/contact"></Header>
        <main className={styles.main}>
         Iot安全云

        

        
        </main>
     
    </>
  );
}

