import React, { useState, useEffect, useRef } from 'react';
import Header from 'components/header';
import Head from 'next/head';
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import Image from 'next/legacy/image'
import Container from 'react-bootstrap/Container';
// import Modal from 'react-bootstrap/Modal';
// import Button from 'react-bootstrap/Button';
import Nav from 'react-bootstrap/Nav';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import styles from '@/styles/Home.module.scss';
import c from './product.module.scss'
import { Section, SectionLeft, SectionRight, SectionBottom, SlideInAnimation } from 'components/framer';
import { useInView } from "framer-motion";

import {
  useTranslation,
} from "next-export-i18n";

export default function Home() {
  const [hydrated, setHydrated] = useState(false);
  const { t } = useTranslation();
  const [activekey, setActivekey] = useState('first')
  const [show, setShow] = useState(false);


  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  const [animates, setAnimater] = useState(true)
  useEffect(() => {
    setHydrated(true);
    function handleScroll() {
      const { scrollTop, clientHeight, scrollHeight } = document.documentElement;
    }
    setTimeout(() => {
      // setApt1(false)
    }, 5000)

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);

    };
  }, [isInView]);
  if (!hydrated) {
    // Returns null on first render, so the client and server match
    return null;
  }

  const handleSelect = (defaultActiveKey: any) => {

    setActivekey(defaultActiveKey)
    // return defaultActiveKey
  }
  return (
    <>

      <Head>
        <title>碳通科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={`${c.part1} part_top`}>
        <Image src='/images/prod_bg.png'
          width={1440}
          height={410} layout='responsive'
        ></Image>
        <Section>
          <Container>
            <h1 className={`${c.h1}`}>CNC</h1>
            <h1 >{t('prd.title')}</h1>
          </Container>

        </Section>  
      </div>
      <div className={c.part2}>

        <div>
          <Tab.Container id="left-tabs-example" defaultActiveKey="first" onSelect={handleSelect}>
            <Container>
              <Row>
                <Col>
                  <Nav variant="" style={{ width: '100%' }} >
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="first">
                        <SlideInAnimation index={1}>
                          <div className={`${activekey == 'first' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>1</span></p>
                          <p className={c.title}>{t('prd.pt1_title')}</p>
                            <div className={c.triangle}></div>
                        </div>
                        </SlideInAnimation>

                      </Nav.Link>
                    </Nav.Item>
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="second">
                        <SlideInAnimation index={2}>
                          <div className={`${activekey == 'second' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>2</span></p>
                          <p className={c.title}>{t('prd.pt2_title')}</p>
                          <div className={c.triangle}></div>
                        </div>
                        </SlideInAnimation>

                      </Nav.Link>
                    </Nav.Item>
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="three">
                        <SlideInAnimation index={3}>
                          <div className={`${activekey == 'three' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>3</span></p>
                          <p className={c.title}>{t('prd.pt3_title')}</p>
                          <div className={c.triangle}></div>
                        </div>
                        </SlideInAnimation>

                      </Nav.Link>
                    </Nav.Item>
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="four">
                        <SlideInAnimation index={4}>
                          <div className={`${activekey == 'four' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>4</span></p>
                          <p className={c.title}>{t('prd.pt4_title')}</p>
                          <div className={c.triangle}></div>
                        </div>
                        </SlideInAnimation>

                      </Nav.Link>
                    </Nav.Item>
                  </Nav>
                </Col>
              </Row>
            </Container>

            <Row className={c.tab_content}>
              <Col>
                <Tab.Content>
                  <Tab.Pane eventKey="first">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <SectionLeft>
                            <Image src='/images/prd_1.png'
                              width={588}
                              height={471} layout='responsive'
                            ></Image>
                          </SectionLeft>

                        </Col>
                        <Col sm={6} xs={12} style={{ alignSelf: 'center' }}>
                          <SectionRight>
                            <div className={c.right_wrap}>
                            <h2>{t('prd.pt1_title')}</h2>
                            <p>{t('prd.pt1_content')}</p>
                              <a href="https://www.cnc.mvgx.com" target='_blank' className={c.btn} >{t('prd.detail')}  &gt;</a>

                          </div>
                          </SectionRight>


                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                  <Tab.Pane eventKey="second">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <SectionLeft>
                            <Image src='/images/prd_2.png'
                              width={588}
                              height={471} layout='responsive'
                            ></Image>
                          </SectionLeft>
                        </Col>
                        <Col sm={6} xs={12} style={{ alignSelf: 'center' }}>
                          <SectionRight>
                            <div className={c.right_wrap}>
                            <h2>{t('prd.pt2_title')}</h2>
                            <p>{t('prd.pt2_content')}</p>
                              <a href="https://www.cnc.mvgx.com" target='_blank' className={c.btn}>{t('prd.detail')}  &gt;</a>
                          </div>
                          </SectionRight>
                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                  <Tab.Pane eventKey="three">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <SectionLeft>
                            <Image src='/images/prd_3.png'
                              width={588}
                              height={471} layout='responsive'
                            ></Image>
                          </SectionLeft>

                        </Col>
                        <Col sm={6} xs={12} style={{ alignSelf: 'center' }}>
                          <SectionRight>
                            <div className={c.right_wrap}>
                            <h2>{t('prd.pt3_title')}</h2>
                            <p>{t('prd.pt3_content')}</p>
                              <a href="https://www.cnc.mvgx.com" target='_blank' className={c.btn}>{t('prd.detail')}  &gt;</a>
                          </div>
                          </SectionRight>


                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                  <Tab.Pane eventKey="four">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <SectionLeft>
                            <Image src='/images/prd_4.png'
                              width={588}
                              height={471} layout='responsive'
                            ></Image>
                          </SectionLeft>
                        </Col>
                        <Col sm={6} xs={12} style={{ alignSelf: 'center' }}>
                          <SectionRight>
                            <div className={c.right_wrap}>
                            <h2>{t('prd.pt4_title')}</h2>
                            <p>{t('prd.pt4_content')}</p>
                              <a href="https://www.cnc.mvgx.com" target='_blank' className={c.btn}>{t('prd.detail')} &gt;</a>
                          </div>
                          </SectionRight>
                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                </Tab.Content>
              </Col>
            </Row>

          </Tab.Container>
        </div>


      </div >
      {/* <Modal show={show} onHide={handleClose} style={{ paddingRight: '0!important' }}>
        <Modal.Body>
          {t('module.msg')}

        </Modal.Body>
      </Modal> */}
    </>
  );
}

