import React, { useState, useEffect, useRef } from 'react';
import Header from 'components/header';
import Head from 'next/head';
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import Image from 'react-bootstrap/Image'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import styles from '@/styles/Home.module.scss';
import c from './product.module.scss'

import {
  useTranslation,
} from "next-export-i18n";

export default function Home() {
  const [hydrated, setHydrated] = useState(false);
  const { t } = useTranslation();
  const [activekey, setActivekey] = useState('first')


  const [animates, setAnimater] = useState(true)
  useEffect(() => {
    setHydrated(true);
    function handleScroll() {
      const { scrollTop, clientHeight, scrollHeight } = document.documentElement;

      // part1
      // setApt1(true);
    }
    setTimeout(() => {
      // setApt1(false)
    }, 5000)

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);

    };
  }, []);
  if (!hydrated) {
    // Returns null on first render, so the client and server match
    return null;
  }

  const handleSelect = (defaultActiveKey: any) => {

    setActivekey(defaultActiveKey)
    // return defaultActiveKey
  }
  return (
    <>

      <Head>
        <title>碳通科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={`${c.part1} part_top`}>
        <Image src='/images/prod_bg.png' width='100%' style={{ height: '410px' }}></Image>
        <h1 className={`animate__animated center ${c.h1} ${animates ? 'animate__fadeInDown' : ''} `}>CNC</h1>
        <h1 className={`animate__animated center ${animates ? 'animate__fadeInDown' : ''} `}>{t('prd.title')}</h1>

      </div>
      <div className={c.part2}>

        <div>
          <Tab.Container id="left-tabs-example" defaultActiveKey="first" onSelect={handleSelect}>
            <Container>
              <Row>
                <Col>
                  {/* {className = "flex-column"} */}
                  <Nav variant="" style={{ width: '100%' }} >
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="first">
                        <div className={`${activekey == 'first' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>1</span></p>
                          <p className={c.title}>{t('prd.pt1_title')}</p>
                          <div className={c.triangle}></div>

                        </div>

                      </Nav.Link>
                    </Nav.Item>
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="second">
                        <div className={`${activekey == 'second' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>2</span></p>
                          <p className={c.title}>{t('prd.pt2_title')}</p>
                          <div className={c.triangle}></div>
                        </div>
                      </Nav.Link>
                    </Nav.Item>
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="three">
                        <div className={`${activekey == 'three' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>3</span></p>
                          <p className={c.title}>{t('prd.pt3_title')}</p>
                          <div className={c.triangle}></div>
                        </div>
                      </Nav.Link>
                    </Nav.Item>
                    <Nav.Item style={{ width: '25%' }}>
                      <Nav.Link eventKey="four">
                        <div className={`${activekey == 'four' ? `${c.active}` : ''}`}>
                          <p className={c.number}><span>4</span></p>
                          <p className={c.title}>{t('prd.pt4_title')}</p>
                          <div className={c.triangle}></div>
                        </div>
                      </Nav.Link>
                    </Nav.Item>
                  </Nav>
                </Col>
              </Row>
            </Container>

            <Row className={c.tab_content}>
              <Col>
                <Tab.Content>
                  <Tab.Pane eventKey="first">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <Image className="p-3 mb-5 bg-white rounded" src='/images/prd_1.png' width='100%' ></Image>
                        </Col>
                        <Col sm={6} xs={12}>
                          <div className={c.right_wrap}>
                            <h2>{t('prd.pt1_title')}</h2>
                            <p>{t('prd.pt1_content')}</p>
                            <a href="" className={c.btn}>{t('prd.detail')}  &gt;</a>
                          </div>

                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                  <Tab.Pane eventKey="second">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <Image className="p-3 mb-5 bg-white rounded" src='/images/prd_2.png' width='100%' ></Image>
                        </Col>
                        <Col sm={6} xs={12}>
                          <div className={c.right_wrap}>
                            <h2>{t('prd.pt2_title')}</h2>
                            <p>{t('prd.pt2_content')}</p>
                            <a href="" className={c.btn}>{t('prd.detail')}  &gt;</a>
                          </div>

                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                  <Tab.Pane eventKey="three">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <Image className="p-3 mb-5 bg-white rounded" src='/images/prd_3.png' width='100%' ></Image>
                        </Col>
                        <Col sm={6} xs={12}>
                          <div className={c.right_wrap}>
                            <h2>{t('prd.pt3_title')}</h2>
                            <p>{t('prd.pt3_content')}</p>
                            <a href="" className={c.btn}>{t('prd.detail')}  &gt;</a>
                          </div>

                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                  <Tab.Pane eventKey="four">
                    <Container>
                      <Row>
                        <Col sm={6} xs={12}>
                          <Image className="p-3 mb-5 bg-white rounded" src='/images/prd_4.png' width='100%' ></Image>
                        </Col>
                        <Col sm={6} xs={12}>
                          <div className={c.right_wrap}>
                            <h2>{t('prd.pt4_title')}</h2>
                            <p>{t('prd.pt4_content')}</p>
                            <a href="" className={c.btn}>{t('prd.detail')} &gt;</a>
                          </div>

                        </Col>
                      </Row>
                    </Container>
                  </Tab.Pane>
                </Tab.Content>
              </Col>
            </Row>
          </Tab.Container>
        </div>


      </div >

    </>
  );
}

