import React, { useEffect, useState } from 'react';
import Header from 'components/header';
import Head from 'next/head';
import Image from 'next/legacy/image'
import Accordion from 'react-bootstrap/Accordion';
import { useAccordionButton } from 'react-bootstrap/AccordionButton';
import Card from 'react-bootstrap/Card';
import { Section, SectionLeft, SectionRight, SectionBottom } from 'components/framer';
import styles from '@/styles/Home.module.css';
import qaStyle from './qa.module.scss'
import {
  useTranslation,
} from "next-export-i18n";

import { useRef } from "react";
import { useInView } from "framer-motion";


export default function Home() {
  const [hydrated, setHydrated] = useState(false);
  const { t } = useTranslation();

  // 动画
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  const items = ['Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7'];
  const [isOpen, setIsOpen] = useState(Array(items.length).fill(true));

  const [activeIndex, setActiveIndex] = useState(1);
  const [show, setShow] = useState(true)

  useEffect(() => {
    setHydrated(true);
  }, [isInView]);
  if (!hydrated) {
    return null;
  }
  const toggleOpen = (index: number) => {
    const newIsOpen = [...isOpen];  //复制当前状态数组
    newIsOpen[index] = !newIsOpen[index];  //切换指定项目的状态
    setIsOpen(newIsOpen);  //设置新状态
  };
  return (
    <>
      <Head>
        <title>碳通科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
        <div className={qaStyle.part1}>
          <Image src='/images/qabg.png'
            width={1440}
            height={410} layout='responsive'
          ></Image>
          <Section>
            <p className={qaStyle.h1}>{t('qa.title')}</p>
          </Section>
        </div>
        <div className={qaStyle.part2}>
          <div className="container">
            {/* 问答区1 */}
            <SectionBottom>
              <div className={qaStyle.according}>
                <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q1')}</span>
                </div>
                  <div className={qaStyle.acbtom} onClick={() => { toggleOpen(0) }}>
                  {isOpen[0] ? (
                      <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                        <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[0] && (
                <div>
                  <div className={qaStyle.content}>
                    <img src="/images/a.png" alt="" />
                    <p>{t('qa.an1')}</p>
                  </div>
                </div>
              )}

            </div>
            </SectionBottom>

            {/* 问答区 2*/}
            <SectionBottom> <div className={qaStyle.according}>
              <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q2')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(1) }}>
                  {isOpen[1] ? (
                    <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                      <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}

                </div>
              </div>
              {isOpen[1] && (
                < div >
                  <div className={qaStyle.content}>
                    <img src="/images/a.png" alt="" />
                    <p>{t('qa.an2')} </p>
                  </div>
                </div>
              )}


            </div></SectionBottom>

            {/* 问答区3 */}
            <SectionBottom>
              <div className={qaStyle.according}>
                <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q3')}</span>
                </div>
                  <div className={qaStyle.acbtom} onClick={() => { toggleOpen(2) }}>
                  {isOpen[2] ? (
                      <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                        <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[2] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p> {t('qa.an3')}</p>
                </div>
              )}

            </div>
            </SectionBottom>

            {/* 问答区4 */}
            <SectionBottom>
              <div className={qaStyle.according}>
                <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span> {t('qa.q4')}</span>
                </div>
                  <div className={qaStyle.acbtom} onClick={() => { toggleOpen(3) }}>
                  {isOpen[3] ? (
                      <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                        <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[3] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an4')}</p>
                </div>
              )}

            </div>
            </SectionBottom>

            {/* 问答区 5*/}
            <SectionBottom>
              <div className={qaStyle.according}>
                <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop} >
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q5')}</span>
                </div>
                  <div className={qaStyle.acbtom} onClick={() => { toggleOpen(4) }}>
                  {isOpen[4] ? (
                      <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                        <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[4] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an4')}</p>
                </div>
              )}

            </div>
            </SectionBottom>

            {/* 问答区 6*/}
            <SectionBottom>
              <div className={qaStyle.according}>
                <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop} >
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q6')}</span>
                </div>
                  <div className={qaStyle.acbtom} onClick={() => { toggleOpen(5) }}>
                  {isOpen[5] ? (
                      <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                        <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[5] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an6')}</p>
                </div>
              )}

            </div>
            </SectionBottom>

            {/* 问答区 7*/}
            <SectionBottom>
              <div className={qaStyle.according}>
                <div className={`myflex ${qaStyle.myflex}`} >
                <div className={qaStyle.actop} >
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q7')}</span>
                </div>
                  <div className={qaStyle.acbtom} onClick={() => { toggleOpen(6) }}>
                  {isOpen[6] ? (
                      <img className={qaStyle.up_arrow} src="/images/green_up_arrow.png" alt="" />
                  ) : (
                        <img className={qaStyle.right_arrow} src="/images/grey_right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[6] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an7')}</p>
                </div>
              )}


            </div>
            </SectionBottom>
          </div>
        </div>
      </div >

    </>
  );
}

