import React, { useEffect, useState } from 'react';
import Header from 'components/header';
import Head from 'next/head';
import Image from 'react-bootstrap/Image'
import Accordion from 'react-bootstrap/Accordion';
import { useAccordionButton } from 'react-bootstrap/AccordionButton';
import Card from 'react-bootstrap/Card';
// import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import qaStyle from './qa.module.scss'
import {
  useTranslation,
} from "next-export-i18n";




export default function Home() {
  const [hydrated, setHydrated] = useState(false);
  const { t } = useTranslation();

  const items = ['Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7'];
  const [isOpen, setIsOpen] = useState(Array(items.length).fill(true));

  const [activeIndex, setActiveIndex] = useState(1);
  const [show, setShow] = useState(true)

  const [animates, setAnimater] = useState(true)
  const [apt1, setApt1] = useState(true)

  useEffect(() => {
    setHydrated(true);

    function handleScroll() {
      const { scrollTop, clientHeight, scrollHeight } = document.documentElement;

      // part1
      // if (scrollTop > 180) {
      //   setApt1_l(true)
      //   setApt1_r(true)
      // }
      // part2

    }
    setTimeout(() => {
      setApt1(false)
    }, 2000)

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);

    };
  }, []);
  if (!hydrated) {
    return null;
  }
  const toggleOpen = (index: number) => {
    const newIsOpen = [...isOpen];  //复制当前状态数组
    newIsOpen[index] = !newIsOpen[index];  //切换指定项目的状态
    setIsOpen(newIsOpen);  //设置新状态

  };
  // useEffect(() => {
  //   setShow(true)
  // }, [])
  return (
    <>

      <Head>
        <title>碳通科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div>
        <div className={qaStyle.part1}>
          <Image src='/images/qabg.png' width='100%'></Image>
          <h1 className={`animate__animated   ${apt1 ? 'animate__fadeInDown' : ''}`}>{t('qa.title')}</h1>
        </div>
        <div className={qaStyle.part2}>
          <div className="container">
            {/* 问答区1 */}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q1')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(0) }}>
                  {isOpen[0] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[0] && (
                <div>
                  <div className={qaStyle.content}>
                    <img src="/images/a.png" alt="" />
                    <p>{t('qa.an1')}</p>
                  </div>
                </div>
              )}


            </div>
            {/* 问答区 2*/}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q2')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(1) }}>
                  {isOpen[1] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}

                </div>
              </div>
              {isOpen[1] && (
                < div >
                  <div className={qaStyle.content}>
                    <img src="/images/a.png" alt="" />
                    <p>{t('qa.an2')} </p>
                  </div>
                </div>
              )}


            </div>
            {/* 问答区3 */}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q3')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(2) }}>
                  {isOpen[2] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[2] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p> {t('qa.an3')}</p>
                </div>
              )}

            </div>
            {/* 问答区4 */}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span> {t('qa.q4')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(3) }}>
                  {isOpen[3] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[3] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an4')}</p>
                </div>
              )}

            </div>
            {/* 问答区 5*/}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop} >
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q5')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(4) }}>
                  {isOpen[4] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[4] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an4')}</p>
                </div>
              )}

            </div>
            {/* 问答区 6*/}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop} >
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q6')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(5) }}>
                  {isOpen[5] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[5] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an6')}</p>
                </div>
              )}

            </div>
            {/* 问答区 7*/}
            <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop} >
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q7')}</span>
                </div>
                <div className={qaStyle.acbtom} onClick={() => { toggleOpen(6) }}>
                  {isOpen[6] ? (
                    <img src="/images/up.png" alt="" />
                  ) : (
                    <img src="/images/right_arrow.png" alt="" />
                  )}
                </div>
              </div>
              {isOpen[6] && (
                <div className={qaStyle.content}>
                  <img src="/images/a.png" alt="" />
                  <p>{t('qa.an7')}</p>
                </div>
              )}


            </div>
            {/* <div className={qaStyle.according}>
              <div className='myflex'>
                <div className={qaStyle.actop}>
                  <img src="/images/q.png" alt="" />
                  <span>{t('qa.q7')}</span>
                </div>
                <div className={qaStyle.acbtom}>
                  <img src="/images/right_arrow.png" alt="" />
                  <p>{t('qa.an7')}</p>
                </div>
              </div>

            </div> */}
          </div>
        </div>
      </div >

    </>
  );
}

