import React, { useState, useEffect, useRef } from 'react';
import ReactEcharts from 'echarts-for-react'
import Header from 'components/header';
import Footer from 'components/footer'
import Chart from 'components/chart'
import Head from 'next/head';
import Image from 'react-bootstrap/Image'
import styles from '@/styles/Home.module.scss';
import aniStyle from '@/styles/animates.module.css';
import Carousel from 'react-bootstrap/Carousel';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Card from 'react-bootstrap/Card';
import postData from './api/hello';

// 翻译
import {
  useTranslation,
} from "next-export-i18n";


export default function Home() {
  // const isMounted = useRef(false)
  const [hydrated, setHydrated] = useState(false);
  const { t } = useTranslation();
  // 动画

  const [animates, setAnimater] = useState(true)
  const [apt2, setApt2] = useState(false)
  const [apt2_l, setApt2_l] = useState(false)
  const [apt2_r, setApt2_r] = useState(false)
  const [apt3, setApt3] = useState(false)
  const [apt4, setApt4] = useState(false)
  const [apt5, setApt5] = useState(false)


  useEffect(() => {
    setHydrated(true);

    function handleScroll() {
      const { scrollTop, clientHeight, scrollHeight } = document.documentElement;
      // console.log(scrollTop)
      // part2
      if (scrollTop > 400) {
        setApt2(true);
        setApt2_l(true)
      }
      // part3
      if (scrollTop > 1300) {
        setApt3(true);
      }
      // part4
      if (scrollTop > 2400) {
        setApt4(true);
      }
      // part5
      if (scrollTop > 3070) {
        setApt5(true);
      }
    }
    setTimeout(() => {
      setApt2(false)
      setApt2_l(false)
      setApt3(false)
      setApt4(false);
      setApt5(false);
    }, 5000)
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);

    };

  }, [])
  if (!hydrated) {
    return null;
  }

  return (
    <>

      <Head>
        <title>碳通科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preload" href="/fonts/PingFangRegular.ttf" as="font" type="font/ttf" ></link>
      </Head>

      {/* 轮播 */}

      <Row>
        <Col>
          <Carousel className={styles.carousel}>
            <Carousel.Item>
              <Image className="d-block w-100" src="/images/index_bg1.png" alt="First slide"
              />
              <Carousel.Caption>
                {/* <div className={styles.ctitle}>kafjwo</div> */}
                <h1 className={`ft_72 ${styles.ft_62} animate__animated ${animates ? 'animate__fadeInDown' : ''}`}>Make Carbon Compliant</h1>
                <p className={`ft_24 mt_56 animate__animated ${styles.pcaru_p} ${animates ? 'animate__fadeInDown' : ''}`}> {t('home.Carousel')}</p>
                {/* <button className='carousel_btn'>合规查询</button> */}
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <Image
                className="d-block w-100"
                src="/images/index_bg1.png"
                alt="Second slide"

              />

              <Carousel.Caption>
                <h1 className={`ft_72 ${styles.ft_62} animate__animated ${animates ? 'animate__fadeInDown' : ''}`}>Make Carbon Compliant</h1>
                <p className={`ft_24 mt_56 animate__animated ${styles.pcaru_p} ${animates ? 'animate__fadeInDown' : ''}`}> {t('home.Carousel')}</p>
                {/* <button className='carousel_btn'>合规查询</button> */}
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <Image
                className="d-block w-100"
                src="/images/index_bg1.png"
                alt="Third slide"

              />

              <Carousel.Caption>
                <h1 className={`ft_72 ${styles.ft_62} animate__animated ${animates ? 'animate__fadeInDown' : ''}`}>Make Carbon Compliant</h1>
                <p className={`ft_24 mt_56 animate__animated ${styles.pcaru_p} ${animates ? 'animate__fadeInDown' : ''}`}> {t('home.Carousel')}</p>
                {/* <button className='carousel_btn'>合规查询</button> */}
              </Carousel.Caption>
            </Carousel.Item>
          </Carousel>
        </Col>
      </Row>

      {/* part2 全球合规优势*/}

      <div className={styles.part2_hg} style={{ position: 'relative', height: '50rem' }}>

        <Row >
          <Col>
            <div className={styles.pt2_postion}>
              <h2 className={`center mt_40 animate__animated opacity_0  ft_48 ${apt2 ? 'animate__fadeInDown' : ''}`}>
                {t('home.gca')}
              </h2>

              <div >
                <Container className={styles.bg_white}>
                  <Row>
                    <Col xs={12} md={8} className={`animate__animated  ${apt2_l ? 'animate__backInLeft' : ''}`}>
                      <h4> {t('home.agc')}</h4>
                      <p className={styles.green_sytle}> {t('home.sft')}</p>
                      <p className={styles.content}> {t('home.uoo')}</p>
                      <div className={styles.flex}>
                        <div className={styles.hg}>
                          <div >
                            <Image src='/images/pocketbook.png' alt=''></Image>
                            <p>{t('home.fac')}</p>
                          </div>
                        </div>
                        <div className={styles.hg}>
                          <div >
                            <Image src='/images/identity.png' alt=''></Image>
                            <p style={{ width: '64px', margin: '4px auto' }}>{t('home.ic')}</p>
                          </div>
                        </div>
                        <div className={styles.hg}>
                          <div >
                            <Image src='/images/goods.png' alt=''></Image>
                            <p style={{ width: '64px', margin: '4px auto' }}>{t('home.pc')}</p>
                          </div>
                        </div>
                        <div className={styles.hg} style={{ marginRight: '0' }}>
                          <div >
                            <Image src='/images/flow.png' alt=''></Image>
                            <p style={{ width: '64px', margin: '4px auto' }}>{t('home.psc')}</p>
                          </div>
                        </div>
                      </div>
                    </Col>
                    <Col xs={6} md={4}>
                      <Image className={`${styles.phone_hide} styles.bg2 animate__animated  ${apt2_l ? 'animate__backInRight' : ''}`} src='/images/bg2_inner.png' alt='' style={{ width: '100%' }}></Image>
                    </Col>
                  </Row>
                </Container>

              </div>
            </div>


            {/* <Tabs></Tabs>   */}
          </Col>
        </Row>

        <Image className={styles.pt2_bg} src='/images/pt2_bg.png' alt='' style={{ width: '100%' }}></Image>
      </div >

      {/* part3 从碳计量到碳资产全程系统服务产品体系 */}
      < Container className={styles.measure} >
        <h2 className={`center animate__animated opacity_0  ft_48 ${apt3 ? 'animate__fadeInDown' : ''}`}>{t('home.p2_fcm')}</h2>
        <div className={`center ${styles.mimg}`}>
          <Image src='/images/measure.png' style={{ width: '100%' }}></Image>
          <div className={styles.mcnc}>CNC <br />碳中和通</div>
          <div className={styles.mcf}>
            {t('home.ps_cf1')} <br />
            {t('home.ps_cf1_1')}
          </div>
          <div className={styles.mcr}>
            {t('home.ps_cf2')} <br />
            {t('home.ps_cf2_1')}
          </div>
          <div className={styles.mcc}>
            {t('home.ps_cf3')}<br />
            {t('home.ps_cf3_1')}
          </div>
          <div className={styles.mcnri}>
            {t('home.ps_cf4')} <br />
            {t('home.ps_cf4_1')}
          </div>
        </div>
      </Container >

      {/*  part4 {全球主要碳交易市场资讯} */}
      < div className={styles.trade} >
        <h2 className={`center mt_40 animate__animated opacity_0 ft_48 ${apt4 ? 'animate__fadeInDown' : ''}`}>{t('home.trde_gm')}</h2>
        <p className={`center animate__animated opacity_0 ${apt4 ? 'animate__fadeInDown' : ''}`}>{t('home.trde_gms')}</p>

        <Container style={{ marginTop: '4.43rem' }}>
          <div className={styles.chartfooter}>
            <Chart />

          </div>
        </Container>
      </div >
      {/* 合作伙伴 */}
      < div className={styles.partners} >
        <h2 className={`center mt_40 animate__animated opacity_0 ft_48 ${apt5 ? 'animate__fadeInDown' : ''}`}>{t('home.Partnership')}</h2>
        <p className={`center animate__animated opacity_0 ${apt5 ? 'animate__fadeInDown' : ''}`}>{t('home.Partnerships')}</p>
        <Container style={{ margin: '4.45rem auto', marginBottom: '6rem' }}>
          <Row className={styles.row_bottom}>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/cejc.png" alt="" />
              </div>
            </Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/potel.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/bcis.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/mvg.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/orac.png" alt="" />
              </div></Col>


            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/shene.png" alt="" />
              </div>
            </Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/apple.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/aden.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/cp.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}> <div className={styles.partnerslogo}>
              <img src="/images/guang.png" alt="" />
            </div>
            </Col>

            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/cetcz.png" alt="" />
              </div>
            </Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/green.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/car.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/cea.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}> <div className={styles.partnerslogo}>
              <img src="/images/bs.png" alt="" />
            </div></Col>

            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/gs.png" alt="" />
              </div>
            </Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/tuv.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/forestry.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}>
              <div className={styles.partnerslogo}>
                <img src="/images/fs.png" alt="" />
              </div></Col>
            <Col xs={4} sm={3} md={2}> <div className={styles.partnerslogo}>
              <img src="/images/carbon1.png" alt="" />
            </div></Col>
          </Row>
        </Container>

      </div >


      <style type="text/css">{`
          .d_card{
            margin-right:2rem;
          }

      `}

      </style>
    </>
  );


}
