import React, { useState, useEffect } from 'react';
import Header from 'components/header';
import Footer from 'components/footer'
import Head from 'next/head';
import Image from 'react-bootstrap/Image'
import styles from '@/styles/Home.module.css';
import aniStyle from '@/styles/animates.module.css';
import Carousel from 'react-bootstrap/Carousel';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Card from 'react-bootstrap/Card';



export default function Home() {

  const [index, setIndex] = useState(0);
  const [isHovering, setIsHovering] = useState(-1);
  const [animates, setAnimater] = useState(true)
  const [aniprt2, setAniprt2] = useState(false)
  const [aniprt2_1, setAniprt2_1] = useState(false)
  const [aniprt2_2, setAniprt2_2] = useState(false)
  const [aniprt3, setAniprt3] = useState(false)
  const [aniprt3_1, setAniprt3_1] = useState(false)
  const [aniprt3_2, setAniprt3_2] = useState(false)
  const [aniprt4, setAniprt4] = useState(false)
  const [aniprt5, setAniprt5] = useState(false)
  const [aniprt6, setAniprt6] = useState(false)
  const [anpt, setAnp] = useState(false)
  const [anptimg, setAnpimg] = useState(false)
  const [anplat, setAnplat] = useState(false)
  const [scrollY, setScrollY] = useState(0);


  useEffect(() => {
    const handleScroll = (e: any) => {
      const scrollTop = (e.srcElement ? e.srcElement.documentElement.scrollTop : false) || window.pageYOffset || (e.srcElement ? e.srcElement.body.scrollTop : 0);
      setScrollY(scrollTop);
      if (scrollTop >= 300) {
        setAniprt2(true)
      }
      if (scrollTop >= 625) {
        setAniprt2_1(true)
      }
      if (scrollTop >= 675) {
        setAniprt2_2(true)
      }
      if (scrollTop >= 1500) {
        setAniprt3(true)
      }
      if (scrollTop >= 1550) {
        setAniprt4(true)
      }
      if (scrollTop >= 2200) {
        setAnp(true)
      }
      if (scrollTop >= 2400) {
        setAnpimg(true)
      }
      if (scrollTop >= 2530) {
        setAniprt3_1(true);
        setAniprt3_2(true)
      }
      if (scrollTop >= 2900) {
        setAnplat(true)
      }
      if (scrollTop >= 3720) {
        setAniprt5(true)
      }
      if (scrollTop >= 4650) {
        setAniprt6(true)
      }
    };
    // eslint-disable-next-line no-undef
    // handleScroll(e);
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  const handleSelect = (selectedIndex: number) => {
    setIndex(selectedIndex);
  };
  const handleMouseOver = (i: number) => {
    setIsHovering(i);
  };

  const handleMouseOut = () => {
    setIsHovering(-1);
  };
  const hoverNum = 41
  const animateHover = () => {
    if (isHovering == 44) {
      setIsHovering(41)
    }
    for (var i = 0; i < 3; i++) {
      setIsHovering(hoverNum + i)
    }
    console.log(isHovering)
  }

  const animateInterval = () => {
    setTimeout(() => {
      setAnimater(false)
    }, 3000)
    // setInterval(() => {
    //   animateHover()
    // }, 4000)
  }
  animateInterval()
  return (
    <>

      <Head>
        <title>碳通科技</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" key="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header href="/"></Header>

      {/* 轮播 */}
      <Row>
        <Col>
          <Carousel activeIndex={index} onSelect={handleSelect} variant="dark">
            <Carousel.Item>
              <Image className="d-block w-100" src="/images/index_bg1.png" alt="First slide"
              />
              <Carousel.Caption>
                <h1 className={`ft_68 animate__animated ${animates ? 'animate__fadeInDown' : ''}`}>受监管的数字资产交易所</h1>
                <p className={`animate__animated ${animates ? 'animate__fadeInDown' : ''}`}>受新加坡金融管理局（”MAS”）批准与监管并获得其授予的牌照</p>
                <button className='carousel_btn'>合规查询</button>
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <Image
                className="d-block w-100"
                src="/images/index_bg1.png"
                alt="Second slide"

              />

              <Carousel.Caption>
                <h1 className='ft_68'>Second slide label</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                <button className='carousel_btn'>合规查询</button>
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <Image
                className="d-block w-100"
                src="/images/index_bg1.png"
                alt="Third slide"

              />

              <Carousel.Caption>
                <h1 className='ft_68'>Third slide label</h1>
                <p>
                  Praesent commodo cursus magna, vel scelerisque nisl consectetur.
                </p>
                <button className='carousel_btn'>合规查询</button>
              </Carousel.Caption>
            </Carousel.Item>
          </Carousel>
        </Col>
      </Row>
      {/* part1-以终为始 目标导向 */}
      <div className={styles.pt1}>
        <Container>
          <Row className={styles.part_1}>
            <Col >
              <h1 className={`center mt_95 animate__animated opacity_0 ${aniprt2 ? 'animate__fadeInDown' : ''}`}>以终为始 目标导向</h1>
              <p className={`center mb_80 animate__animated opacity_0 ${aniprt2 ? 'animate__fadeInDown' : ''}`} >这是一句内容，可以长可以很简短</p>
            </Col>
          </Row>
        </Container>

        <Container >
          <Row xs={1} md={3} className={`g-3 animate__animated  opacity_0 ${aniprt2_1 ? 'animate__fadeInUp' : ''}`} style={{ marginBottom: '1rem' }}>
            <Col>
              <Card border="light" className={styles.cards} onMouseOver={() => handleMouseOver(0)}
                onMouseOut={handleMouseOut}
              >
                <div className={isHovering === 0 ? styles.cardshover : styles.cardshide} >
                  <Card.Body>
                    <Card.Title>碳足迹核查</Card.Title>
                    <Card.Text className='ft14'>
                      企业通过系统实现碳排放记录、计算及管理。为企业提供碳足迹数据自动化采集，整理，测算，自动生成清册及盘查报告。企业通过系统可以直观看到不同部门及模块碳排放占比，自动化的数据处理与报告生成，确保数据来源准确性的同时也提高了企业的碳排放管理效率。
                    </Card.Text>

                  </Card.Body>
                </div>
                <div className={isHovering === 0 ? styles.hide : ''} >
                  <Card.Img variant="top" src="/images/zj.png" />
                  <Card.Body>
                    <Card.Text className={styles.card_text}>
                      碳足迹核查
                    </Card.Text>
                  </Card.Body>
                </div>

              </Card>
            </Col>
            <Col>
              <Card border="light" className={styles.cards} onMouseOver={() => handleMouseOver(1)}
                onMouseOut={handleMouseOut}
              >
                <div className={isHovering === 1 ? styles.cardshover : styles.cardshide} >
                  <Card.Body>
                    <Card.Title>碳足迹盘查</Card.Title>
                    <Card.Text className='ft14'>
                      企业通过系统实现碳排放记录、计算及管理。为企业提供碳足迹数据自动化采集，整理，测算，自动生成清册及盘查报告。企业通过系统可以直观看到不同部门及模块碳排放占比，自动化的数据处理与报告生成，确保数据来源准确性的同时也提高了企业的碳排放管理效率。
                    </Card.Text>

                  </Card.Body>
                </div>
                <div className={isHovering === 1 ? styles.hide : ''} >
                  <Card.Img variant="top" src="/images/pca.png" />
                  <Card.Body>

                    <Card.Text className={styles.card_text}>
                      碳足迹盘查
                    </Card.Text>
                  </Card.Body>
                </div>

              </Card>
            </Col>
            <Col>
              <Card border="light" className={styles.cards} onMouseOver={() => handleMouseOver(2)}
                onMouseOut={handleMouseOut}
              >
                <div className={isHovering === 2 ? styles.cardshover : styles.cardshide} >
                  <Card.Body>
                    <Card.Title>碳信用登记</Card.Title>
                    <Card.Text className='ft14'>
                      企业通过系统实现碳减排数据自动化收集、进行碳减排量管理、登记及认证。将碳减排项目从登记注册、到资料上传、到信息审查、最后获得减排认证全流程通过系统实现，大幅提升碳信用数据登记效率。并且系统为企业提供项目详情、进度预览，及多维度的数据统计。支持区域资源碳减排从项目到碳信用的系统化，流程化认证。

                    </Card.Text>

                  </Card.Body>
                </div>


                <div className={isHovering === 2 ? styles.hide : ''} >
                  <Card.Img variant="top" src="/images/kf.png" />
                  <Card.Body>
                    <Card.Text className={styles.card_text}>
                      碳信用登记
                    </Card.Text>
                  </Card.Body>
                </div>




              </Card>
            </Col>
          </Row>
          <Row xs={1} md={3} className={`g-3 animate__animated  opacity_0 ${aniprt2_2 ? 'animate__fadeInUp' : ''}`}>
            <Col>
              <Card border="light" className={styles.cards} onMouseOver={() => handleMouseOver(3)}
                onMouseOut={handleMouseOut}>
                <div className={isHovering === 3 ? styles.cardshover : styles.cardshide} >
                  <Card.Body>
                    <Card.Title>碳中和核证</Card.Title>
                    <Card.Text className='ft14'>
                      系统帮助企业通过自愿减排量抵扣注销流程，进行中和并获得权威机构证书。通过系统汇集多区域，多标准，多机构的碳中和流程，帮助企业在碳中和过程中全面了解平台能力和执行结果，满足各种需求基础的碳中和行为，获取碳中和证书。
                    </Card.Text>

                  </Card.Body>
                </div>
                <div className={isHovering === 3 ? styles.hide : ''} >
                  <Card.Img variant="top" src="/images/hzz.png" />
                  <Card.Body>
                    <Card.Text className={styles.card_text}>
                      碳中和核证
                    </Card.Text>
                  </Card.Body></div>

              </Card>
            </Col>
            <Col>
              <Card border="light" className={styles.cards} onMouseOver={() => handleMouseOver(4)}
                onMouseOut={handleMouseOut}>
                <div className={isHovering === 4 ? styles.cardshover : styles.cardshide} >
                  <Card.Body>
                    <Card.Title>碳中和运营评级</Card.Title>
                    <Card.Text className='ft14'>
                      碳中和运营指数评估可以帮助企业了解企业自身碳中和程度与行业领先水平的差距，从而管控风险；高评级的企业可以从市场中脱颖而出，意味着更好的环境友好管理水平与承担了更多的社会责任，有利于品牌建设。在评价之后，可以帮助企业在碳中和趋势下符合政策要求、降低运营成本，获得减碳收益。
                    </Card.Text>

                  </Card.Body>
                </div>
                <div className={isHovering === 4 ? styles.hide : ''} >
                  <Card.Img variant="top" src="/images/pj.png" />
                  <Card.Body>

                    <Card.Text className={styles.card_text}>
                      碳中和运营评级
                    </Card.Text>
                  </Card.Body>
                </div>

              </Card>
            </Col>
            <Col>
              <Card border="light" className={styles.cards} onMouseOver={() => handleMouseOver(5)}
                onMouseOut={handleMouseOut}>
                <div className={isHovering === 5 ? styles.cardshover : styles.cardshide} >
                  <Card.Body>
                    <Card.Title>Card Title</Card.Title>
                    <Card.Text className='ft14'>
                      Some quick example text to build on the card title and make up the
                      bulk of the content.
                    </Card.Text>

                  </Card.Body>
                </div>
                <div className={isHovering === 5 ? styles.hide : ''} >
                  <Card.Img variant="top" src="/images/cloud.png" />
                  <Card.Body>
                    <Card.Text className={styles.card_text}>
                      IoT安全云
                    </Card.Text>
                  </Card.Body>
                </div>

              </Card>
            </Col>
          </Row>

        </Container>

      </div>
      {/* part2 全球合规优势*/}

      <div style={{ position: 'relative' }}>

        <Row >
          <Col>
            <div className={styles.pt2_postion}>
              <h2 className={`center mt_40 animate__animated opacity_0 ${aniprt3 ? 'animate__fadeInDown' : ''}`}>全球合规优势</h2>
              <p className={`center mb_80 animate__animated opacity_0 ${aniprt3 ? 'animate__fadeInDown' : ''}`}>严格按照各国法律标准为交易双方提供资产权益和法律责任的记录和存证</p>


              <div >
                <Container className={styles.bg_white}>
                  <Row>
                    <Col xs={12} md={8} className={`animate__animated opacity_0 ${aniprt4 ? 'animate__backInLeft' : ''}`}>
                      <h4>关于全球合规</h4>
                      <p className={styles.green_sytle}>严格按照各国法律标准为交易双方提供资产权益和法律责任的记录和存证</p>
                      <p>MVGX运用自身金融资质和经验，作为合规基础设施，不直接面对客户的终端用户，只在客户背后帮助客户搭建合规业务底层和通道，以支持客户在安全、合规的基础之上开展业务，服务前端用户。</p>
                      <div className={styles.flex}>
                        <div className={styles.hg}>
                          <div >
                            <Image src='/images/pt3_1.png' alt=''></Image>
                            <p>身份合规</p>
                          </div>
                        </div>
                        <div className={styles.hg}>
                          <div >
                            <Image src='/images/pt3_1.png' alt=''></Image>
                            <p>产品合规</p>
                          </div>
                        </div>
                        <div className={styles.hg}>
                          <div >
                            <Image src='/images/pt3_1.png' alt=''></Image>
                            <p>资金合规</p>
                          </div>
                        </div>
                        <div className={styles.hg} style={{ marginRight: '0' }}>
                          <div >
                            <Image src='/images/pt3_1.png' alt=''></Image>
                            <p>流程合规</p>
                          </div>
                        </div>
                      </div>
                    </Col>
                    <Col xs={6} md={4}>
                      <Image className={`phone_hide styles.bg2 animate__animated opacity_0 ${aniprt4 ? 'animate__backInRight' : ''}`} src='/images/bg2_inner.png' alt='' style={{ width: '100%' }}></Image>
                    </Col>
                  </Row>
                </Container>

              </div>
            </div>


            {/* <Tabs></Tabs>   */}
          </Col>
        </Row>

        <Image className='pt2_bg' src='/images/pt2_bg.png' alt='' style={{ width: '100%' }}></Image>
      </div>
      {/* 平台亮点 */}
      <div className='pt3'>
        <div className={styles.pt3_bg}>
          <h2 className={`center mt_40 animate__animated opacity_0 ${anpt ? 'animate__fadeInDown' : ''}`}>平台亮点</h2>
          <p className={`center mb_80 animate__animated opacity_0 ${anpt ? 'animate__fadeInDown' : ''}`}>以Value-Added目标代替规划咨询</p>
          <Container>
            <Row>
              <Col className={`animate__animated opacity_0 ${aniprt3_1 ? 'animate__fadeInLeft' : ''}`}>
                <div className={styles.pt3_img}>

                  <Image src="/images/tick.png" alt="" />
                  <span>受监管的数字资产交易所</span>
                  <p>受新加坡金融管理局(“MAS”)批准与监管并获得其授予的牌照</p>
                </div>
                <div className={styles.pt3_img}>
                  <Image src="/images/tick.png" alt="" />
                  <span>受监管的数字资产交易所</span>
                  <p>受新加坡金融管理局(“MAS”)批准与监管并获得其授予的牌照</p>
                </div>
                <div className={styles.pt3_img}>
                  <Image src="/images/tick.png" alt="" />
                  <span>受监管的数字资产交易所</span>
                  <p>受新加坡金融管理局(“MAS”)批准与监管并获得其授予的牌照</p>
                </div>
              </Col>
              <Col style={{ textAlign: 'center' }} className={styles.pt3_img_col}>
                <Image className={`prt3_img animate__animated  ${anptimg ? 'animate__zoomIn' : ''}`} src='/images/prt3_4.png' alt='' style={{ width: '17rem' }}></Image>
              </Col>
              <Col className={`animate__animated opacity_0 ${aniprt3_1 ? 'animate__fadeInRight' : ''}`}>
                <div className={styles.pt3_img}>
                  <Image src="/images/tick.png" alt="" />
                  <span>受监管的数字资产交易所</span>
                  <p>受新加坡金融管理局(“MAS”)批准与监管并获得其授予的牌照</p>
                </div>
                <div className={styles.pt3_img}>
                  <Image src="/images/tick.png" alt="" />
                  <span>受监管的数字资产交易所</span>
                  <p>受新加坡金融管理局(“MAS”)批准与监管并获得其授予的牌照</p>
                </div>
                <div className={styles.pt3_img}>
                  <Image src="/images/tick.png" alt="" />
                  <span>受监管的数字资产交易所</span>
                  <p>受新加坡金融管理局(“MAS”)批准与监管并获得其授予的牌照</p>
                </div>

              </Col>
            </Row>
          </Container>
        </div>
      </div>
      {/* 核心技术 */}
      <div className='pt4'>
        <h2 className={`center mt_40 animate__animated opacity_0 ${anplat ? 'animate__fadeInDown' : ''}`}>核心技术</h2>
        <p className={`center mb_80 animate__animated opacity_0 ${anplat ? 'animate__fadeInDown' : ''}`}>以Value-Added目标代替规划咨询</p>
        <Container>
          <Row>
            <Col>
              <div className={styles.circle}>
                <Image className={styles.circle_img} alt='' src='/images/circle.png'></Image>

                {/* 云边计算 */}
                <div className={styles.cri_1}>
                  <Image className={`phone_hide ${styles.cri_arrow1} ${aniStyle.flash}`} src='images/arrow_left_or.png' alt=''></Image>
                  {/* hover——content */}
                  <div className={styles.circle_wrap} onMouseOver={() => handleMouseOver(41)}
                    onMouseOut={handleMouseOut}>
                    <div className={isHovering === 41 ? styles.circle_hover : styles.cardshide} style={{ paddingLeft: '4rem', paddingTop: '2rem' }}>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>安全智能硬件采集系统</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>多数据多标准处理能力</span>
                      </p>

                    </div>
                    <div className={isHovering === 41 ? styles.hide : ''}>
                      <Image src='/images/book1.png' alt=''></Image>
                      <span>云边计算</span>
                    </div>

                  </div>
                  <Image className={`phone_hide ${styles.cri_arrow2} ${aniStyle.flash}`} src='images/arrow_left_or.png' alt=''></Image>
                </div>
                {/* 安全数据 */}

                <div className={styles.cri_2}>

                  <div className={styles.circle_wrap} onMouseOver={() => handleMouseOver(42)}
                    onMouseOut={handleMouseOut}>
                    <div className={isHovering === 42 ? styles.circle_hover : styles.cardshide} >
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>经国内外多标准平台认证的算法</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>AIOT数据和各类因子匹配算法</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>全球跨平台跨国界碳中和系统</span>
                      </p>
                    </div>
                    <div className={isHovering === 42 ? styles.hide : ''}>
                      <Image src='/images/book2.png' alt=''></Image>
                      <span>安全数据</span>
                    </div>

                  </div>
                </div>
                {/* 碳资产认证 */}
                <div className={styles.cri_3}>
                  <Image className={`phone_hide ${styles.cri_arrow1} ${aniStyle.flash}`} src='images/arrow_right_or.png' alt=''></Image>
                  <div className={styles.circle_wrap} onMouseOver={() => handleMouseOver(43)}
                    onMouseOut={handleMouseOut}>
                    <div className={isHovering === 43 ? styles.circle_hover : styles.cardshide}>
                      <p>
                        <Image src='/images/tick.png'></Image>
                        <span>经国内外多标准平台认证的算法</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png'></Image>
                        <span>AIOT数据和各类因子匹配算法</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png'></Image>
                        <span>全球跨平台跨国界碳中和系统</span>
                      </p>
                    </div>
                    <div className={isHovering === 43 ? styles.hide : ''}>
                      <Image src='/images/book3.png' alt=''></Image>
                      <span>碳资产认证</span>
                    </div>

                  </div>
                  <Image className={`phone_hide ${styles.cri_arrow2} ${aniStyle.flash}`} src='images/arrow_right_or.png' alt=''></Image>
                </div>
                {/* 智能能源管理  */}
                <div className={styles.cri_4}>

                  <div className={styles.circle_wrap} onMouseOver={() => handleMouseOver(44)}
                    onMouseOut={handleMouseOut}>
                    <div className={isHovering === 44 ? styles.circle_hover : styles.cardshide}>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>经国内外多标准平台认证的算法</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>AIOT数据和各类因子匹配算法</span>
                      </p>
                      <p>
                        <Image src='/images/tick.png' alt=''></Image>
                        <span className='ft14'>全球跨平台跨国界碳中和系统</span>
                      </p>
                    </div>
                    <div className={isHovering === 44 ? styles.hide : ''}>
                      <Image src='/images/book4.png' alt=''></Image>
                      <span>智能能源管理</span>
                    </div>

                  </div>
                </div>
              </div>



            </Col>
          </Row>
        </Container>
      </div>
      {/* 核心服务 */}
      <div className='pt5'>
        <div className={styles.pt5}>
          <h2 className={`center mt_40 animate__animated opacity_0 ${aniprt5 ? 'animate__fadeInDown' : ''}`}>核心服务</h2>
          <p className={`center mb_80 animate__animated opacity_0 ${aniprt5 ? 'animate__fadeInDown' : ''}`}>以Value-Added目标代替规划咨询</p>
          <Container>
            <div className={styles.pt5_content}>
              <div className={styles.row1}>
                <div onMouseOver={() => handleMouseOver(51)}
                  onMouseOut={handleMouseOut}>
                  <aside className={isHovering === 51 ? styles.corehover : styles.cardshide}>
                    <h5>智能设备管理 </h5>
                    <p>补充核心物联网设备，配合大厂数据采集监控设备运行状态，提升80%管理准确性，实现设备最佳性能。 </p>
                  </aside>
                  <aside className={isHovering === 51 ? styles.hide : ''}>
                    <Image src='/images/pt6_1.png' alt=''></Image>
                    <p>智能设备管理 </p>
                  </aside>

                </div>
                <div onMouseOver={() => handleMouseOver(52)}
                  onMouseOut={handleMouseOut}>
                  <aside className={isHovering === 52 ? styles.corehover : styles.cardshide}>
                    <h5>智能运营  </h5>
                    <p>以技术创新为源动力改善管理方式，提供数字化运营解决方案及服务，同比下降35%+运营管理成本。%管理准确性，实现设备最佳性能。 </p>
                  </aside>
                  <aside className={isHovering === 52 ? styles.hide : ''}>
                    <Image src='/images/pt6_2.png' alt=''></Image>
                    <p>智能运营 </p>
                  </aside>

                </div>
              </div>
              <div className={styles.row2}>
                <div onMouseOver={() => handleMouseOver(53)}
                  onMouseOut={handleMouseOut}>
                  <aside className={isHovering === 53 ? styles.corehover : styles.cardshide}>
                    <h5>智能能源管理   </h5>
                    <p>提供低碳零碳能源规划，优化能源使用效率，拥抱绿色可持续发展。</p>
                  </aside>
                  <aside className={isHovering === 53 ? styles.hide : ''}>
                    <Image src='/images/book4.png' alt=''></Image>
                    <p>智能能源管理</p>
                  </aside>

                </div>
                <div onMouseOver={() => handleMouseOver(54)}
                  onMouseOut={handleMouseOut}>
                  <aside className={isHovering === 54 ? styles.corehover : styles.cardshide}>
                    <h5>一站式碳中和服务   </h5>
                    <p>以技术创新为源动力改善管理方式，提供数字化运营解决方案及服务，同比下降35%+运营管理成本。</p>
                  </aside>
                  <aside className={isHovering === 54 ? styles.hide : ''}>
                    <Image src='/images/pt6_3.png' alt=''></Image>
                    <p>一站式碳中和服务  </p>
                  </aside>

                </div>
              </div>
              <div className={styles.row3}>
                <div onMouseOver={() => handleMouseOver(55)}
                  onMouseOut={handleMouseOut}>
                  <aside className={isHovering === 55 ? styles.corehover : styles.cardshide}>
                    <h5>工业数字孪生    </h5>
                    <p>uu </p>
                  </aside>
                  <aside className={isHovering === 55 ? styles.hide : ''}>
                    <Image src='/images/pt6_4.png' alt=''></Image>
                    <p>工业数字孪生  </p>
                  </aside>

                </div>


              </div>
            </div>
          </Container>

        </div>

      </div >
      {/* 国际碳金融资产开发SaaS平台 */}
      < div className='pt6' >
        <div className={styles.pt6}>
          <Image src='./images/sass_bj.png' alt='' style={{ width: '100%' }}></Image>
          <div>
            <h2 className={`center mt_40 animate__animated opacity_0 ${aniprt6 ? 'animate__fadeInDown' : ''}`}>国际碳金融资产开发SaaS平台</h2>
            <p className={`center mb_80 animate__animated opacity_0 ${aniprt6 ? 'animate__fadeInDown' : ''}`} style={{ color: '#eee' }}>以Value-Added目标代替规划咨询</p>
            <button className={`animate__animated ${aniprt6 ? 'animate__fadeInDown' : ''}`}>立刻了解</button>
          </div>
        </div>
      </div >
      <Footer />

      <style type="text/css">{`
          .d_card{
            margin-right:2rem;
          }

      `}

      </style>
    </>
  );
}
